#!/usr/bin/env bash
# gives you information about the bestschool file

FILE="bestschool"
if [ -e "$FILE" ]; then
    echo "$FILE file exists"
    if [ -s "$FILE" ]; then
	echo "bestschool file is not empty"
    else
	echo "bestschool file is empty"
    fi
    if [ -f "$FILE" ]; then
	echo "bestschool is a regular file"
    fi
else
    echo "bestschool file does not exist"
fi
